#pragma once
#include "stdafx.h"

// this header file contains the help information

std::vector<std::string> help_text = {
	"-----------------------------------------------",
	"Overview",
	"-----------------------------------------------",
	"Stratagem is a turn-based grid-based strategy game. Two players take turns to move and attack with their units and the game is won when the opponent has no units left.",
	"",
	"-----------------------------------------------",
	"Actions",
	"-----------------------------------------------",
	"On a turn each unit can move and attack once(in either order). When a unit has taken one of these actions it must take the other immediately or pass for the turn.", 
	"",
	"When selecting a unit on the map, the context menu lists the actions that are available for the unit. When an action has been selected the valid targets will be highlighted red (tiles when moving and units when attacking).",
	"",
	"Moving",
	"-----------------------------------------------",
	"Each unit has a maximum amount of movement that can be used during a movement action and each terrain type has a movement cost required to enter it. The values of these attributes for the different units and terrain types are detailed in their respective sections below.",
	"",
	"Attacking",
	"-----------------------------------------------",
	"Each unit has an attack damage stat, an armour stat, an armour penetration stat and an attack range stat. Each terrain type has an attack and defense modifier. The values of these stats are detailed below.",
	"",
	"Attack damage is the raw damage, this damage is reduced by armour, armour is reduced by armour penetration(but can never fall below zero). Terrain modifiers are applied after unit modifiers and can provide an increase or decrease to the damage done and received by a unit on the terrain tile. Attack range determines the maximum range a unit can target an enemy for an attack.",
	"",
	"If a unit\'s hit points fall to 0 when receiving an attack the unit dies and is removed from the map.",
	"",
	"-----------------------------------------------",
	"The Map",
	"-----------------------------------------------",
	"The game is played on a map of tiles. Each tile has a terrain type which affects an occupying unit\'s attacking and defensive capability. Each terrain type also has a movement cost associated with moving into the tile during a unit\'s movement action.", 
	"",
	"When starting a game you can choose a map from those available and then place your units within the placement region of the map(left 3 tile columns for player 1 and right 3 tile columns for player 2).",
	"",
	"-----------------------------------------------",
	"Terrain Type Stats",
	"-----------------------------------------------",
	"Plains:",
	"Movement Cost = 1, Attack Modifier = 0,  Defense Modifier = 0",
	"",
	"Forest:",
	"Movement Cost = 2, Attack Modifier = 0,  Defense Modifier = 2",
	"",
	"Mountains:",
	"Movement Cost = 3, Attack Modifier = -1, Defense Modifier = 3",
	"",
	"Water:",
	"Units cannot enter water tiles.",
	"",
	"-----------------------------------------------",
	"Unit Stats",
	"-----------------------------------------------",
	"Warrior:",
	"Starting HP = 30, Armour = 3, Movement Range = 2, Attack Range = 1, Attack Damage = 8, Armour Penetration = 1",
	"",
	"Rogue:",
	"Starting HP = 25, Armour = 1, Movement Range = 3, Attack Range = 1, Attack Damage = 9, Armour Penetration = 0",
	"",
	"Archer:",
	"Starting HP = 20, Armour = 0, Movement Range = 2, Attack Range = 2, Attack Damage = 8, Armour Penetration = 3"
};